name: build

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  haskell:
    strategy:
      fail-fast: false
      matrix:
        include:
          - { os: ubuntu-latest }

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - uses: cachix/install-nix-action@v15
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - uses: cachix/cachix-action@v10
        with:
          name: amazonka
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - run: nix build
      - run: nix flake check
